set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
#set-option -g default-command "reattach-to-user-namespace -l /opt/local/bin/bash --login"
set -g default-terminal "tmux-256color"
set -g @plugin 'jabirali/tmux-tilish'
set -g @plugin 'dracula/tmux'

# to install new plugins hit Ctrl+b then Shift+i while in a tmux session

run '~/.tmux/plugins/tpm/tpm'

# reccomended lines for tilish
set -s escape-time 0
set -g base-index 1

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# status bar default
# I would like to add more to this. Tilish changed the status bar and this 
# is a quick fix to get it closer to normal.        
# if you run "tmux -Lfoo -f/dev/null start\; show -g" 
# it will show you the status bar before changes
set -g status on
set -g status-interval 20 
set -g status-justify left
set -g status-keys vi
set -g status-left " [#S] "
set -g status-left-length 15
set -g status-left-style default
set -g status-position bottom
set -g status-right " %D "
set -g status-right-length 40
set -g status-right-style default
set -g status-style fg=black,bg=blue

set -g window-status-format " #I #W "

# set -g window-status-current-format "#I #W"
# set -g window-status-current-style bg=cyan

# Reload the file with Prefix r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# bind-key v split-window -h
# bind-key s split-window -v

# bind-key J resize-pane -D 5
# bind-key K resize-pane -U 5
# bind-key H resize-pane -L 5
# bind-key L resize-pane -R 5

# Vim style pane selection
# bind h select-pane -L
# bind j select-pane -D 
# bind k select-pane -U
# bind l select-pane -R

# to apply any changes to this config fill run: tmux source ~/.tmux.conf
